<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CartStoreRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'product_id'=>'required|exists:products,id',
            'quantity'=>'required|numeric',
            'temp_user_id' => 'required',
        ];
    }

    public function validationData()
    {
        $user_id = auth('sanctum')->check()&& auth()->user() !== null ? auth()->id():null;
        return array_merge($this->all(),['user_id'=>$user_id]); // TODO: Change the autogenerated stub
    }
}
