<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OrderStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'user_id'    => 'required|integer|exists:users,id',
            'address_id' => 'required|integer|exists:addresses,id',
            'include_points' => 'required|bool',
            'serial_number' => 'required',
        ];
    }

    public function validationData()
    {
        return array_merge($this->all(),['user_id',auth('auth:sanctum')->id()]); // TODO: Change the autogenerated stub
    }
}
