<?php

namespace App\Http\Requests;

use App\Models\Rate;
use Illuminate\Foundation\Http\FormRequest;

class RatesStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'user_id'      => 'required|integer|exists:users,id',
            'ratable_type' => 'required|integer|in:'.collect(Rate::RATABLE_TAYPES)->implode(','),
            'ratable_id'   => 'required|integer',
            'comment'      => 'nullable|string',
            'rate_number'  => 'required|numeric',
        ];
    }

    public function validationData()
    {
        return array_merge($this->all(),['user_id'=>auth('sanctum')->id()]); // TODO: Change the autogenerated stub
    }
}
